apiVersion: apps/v1 
kind: Deployment
metadata:
  name: gogs
  labels:
    app: gogs
spec:
  selector:
    matchLabels:
      app: gogs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
      - image: docker.io/gogs/gogs
        name: gogs
        env:
        - name: GOGS_HOST
          value: postgres
        - name: GOGS_PASSWORD
          value: redhat
        ports:
        - containerPort: 3000
          name: gogs
---
apiVersion: v1
kind: Service
metadata:
  name: gogs-svc
spec:
  type: NodePort
  selector:
          app: gogs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30123
