kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.22.33
    path: "/nfs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim1
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
