apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_DATABASE
          value: kucl
        ports:
        - containerPort: 3306
          name: mysql
#Create a service for mysql
#kubectl expose deployment mysql --port=3306 --target-port=3306
