apiVersion: v1
kind: Service
metadata:
        name: svc1
spec:
        type: NodePort
        selector:
                class: web
        ports:
                - protocol: TCP
                  port: 8080
                  targetPort: 80
                
