kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:  
    - ReadWriteMany
  nfs:
    server: 172.31.25.214
    path: "/mysql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:   
  name: pv-claim1
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
