kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv2
  labels:
    app: wp
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:  
    - ReadWriteMany
  nfs:
    server: 172.31.25.214
    path: "/nfs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:   
  name: pv-claim2
  labels:
    app: wp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
